// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsJHhAvATaxEA3oS9tkl1nI8O_teP3qcE',
    appId: '1:956531075376:web:2d21c6f2bbe132434540f5',
    messagingSenderId: '956531075376',
    projectId: 'dorm-app-261c5',
    authDomain: 'dorm-app-261c5.firebaseapp.com',
    storageBucket: 'dorm-app-261c5.appspot.com',
    measurementId: 'G-ZJVE8DT118',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv6YTcnFru8R15yGHzjP3ax1PN19QPbJg',
    appId: '1:956531075376:android:cf7b998eb6d9851f4540f5',
    messagingSenderId: '956531075376',
    projectId: 'dorm-app-261c5',
    storageBucket: 'dorm-app-261c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxTbX_FSXIR1G_M64YnBK7WuFtqQUyBfg',
    appId: '1:956531075376:ios:1b0c85dd1842be914540f5',
    messagingSenderId: '956531075376',
    projectId: 'dorm-app-261c5',
    storageBucket: 'dorm-app-261c5.appspot.com',
    iosClientId: '956531075376-kp7edkttjmaksv36rt5vbunlp6mfqnku.apps.googleusercontent.com',
    iosBundleId: 'com.palipa.dormApp',
  );
}
